### ISSUE TITLE
`run_async` is not async!

### ISSUE THREAD

**Issue by fopina** [surface-security/django-dkron#18]
https://github.com/surface-security/django-dkron/blob/072084f7113b831f6895a275e584010baf1d51a8/dkron/utils.py#L270

WoW after so long using this in Surface and just now I've noticed that job creation in `run_async` does wait for the job to terminate.... 🤯 

Opened issue in dkron https://github.com/distribworks/dkron/issues/1268 to confirm this is intended behaviour.

It seems that `runJob` also does it, so reverting back to the way it was before (2+ years ago) won't help.

We can try to use `@at TIME_1SECOND_IN_THE_FUTURE` though it sounds too hacky and error-prone (app and dkron having skewed clocks).

**Comment by gsilvapt** [comment]
I'm leaving this issue open as a reference to the issue created upstream. For now, we have merged your patch to this, although we would very much like to see this change in `dkron` directly.

**Comment by gsilvapt** [comment]
Closing this issue as this was resolved in #19 .

**Comment by fopina** [comment]
Following up on #23 and since it has been fixed upstream, I'll open PR to go back to old call *if* version is >= 3.2.3 👌
